### ISSUE TITLE
Support for a Deny/Exception Pattern of endpoints with HttpInterceptorConfig

### ISSUE THREAD

**Issue by mharrisn** [auth0/auth0-angular#120]
### Describe the problem you'd like to have solved

> This request is a follow up to https://github.com/auth0/auth0-angular/issues/74. I have a use case that I think may more clearly indicate the need for this functionality. Our .Net Core Web API contains 15 Controllers. 3 of these controllers do not require authorization headers for various reasons. Based on the documentation, my understanding is that I would need to specify each of the 12 Controller that need Authorization as "Allowed".

### Describe the ideal solution

> I think a better option would be to add support for an 'except' indicator:
```
httpInterceptor: {
        allowedList: [
          {
            // Allow all API Endpoints
            uri: 'https://MY_DOMAIN/api/*',
          }, {
            // Except this pattern
            uri: '!https://MY_DOMAIN/api/setup*'
          }, {
            // And this pattern
            uri: '!https://MY_DOMAIN/api/public*'
          }
        ]
      }
```

## Alternatives and current work-arounds

> I understand the intent of an explicit allowed list, but without the flexibility to easily exclude a subset, it forces developers into more error prone scenarios. If my API needs a new Controller, I would need to remember to manage this list, or suffer frustration of troubleshooting why no token is being passed. Is it an issue with you Rule? Your Action? The App/API config? I believe it simply make for a more consumable, forgivable API.  

### Additional context

> This ! indicator's behavior is inline with other similar implementations like glob patterns.

**Comment by frederikprijck** [comment]
Hey @mharrisn ,

Thanks for reporting this.

I do want to point out that all of this is still possible if you would set up your URLs in such a way that it is clear to differentiate between public and private methods. You could have a different suffix for private urls and use that in the HTTP Interceptor without needed to specify all 12 Controllers.

for example:

```
https://MY_DOMAIN/api
https://MY_DOMAIN/private-api (or https://private.MY_DOMAIN/api)

httpInterceptor: {
        allowedList: [
          {
            // Allow all API Endpoints
            uri: 'https://MY_DOMAIN/private-api/*',
          },
        ]
      }
```

If your design is set up in such a way that you have a mix of public and private endpoints on the same root URL (https://MY_DOMAIN/api), I think it is expected that you might find yourself in a situation where you need to be explicit about it (even outside things like our SDK).

Having a way to exclude URLs would work for your situation. But what would you do when you have 12 private and 12 public methods? You most likely will have 12 entries in the httpInterceptor config anyway (be it 12 includes or 12 excludes), so you haven't really solved anything with using an exclude approach. That's why I feel like the proposed solution is not a scalable solution to your problem.

The way you set up your backend is of course not our decision to make, I just want to point out there are solutions to the problem using the current situation without changes to the SDK, which is why we have been hesitant on implementing this.

I also understand that the solution I propose might not work in all situations, but could help in some.

Personally, instead of using the proposed, glob-like, `!`, I am more a fan of either allowing regex or adding something like an urlMatcher, which would give you full control:

```
{
   allowedList: [
     { 
       uriMatcher: (uri) => {} 
     }
   ]
},
```

Using a matcher function as above would be more complex to use, but would allow for full flexibility.
What would you think about that? Would that solve the problem in a feasible way?

Anyway, I will leave this open for the time being and get back to this after having a conversation internally as well.

**Comment by mharrisn** [comment]
Hello and thank you for the response. You are correct that if there was
close to an equal balance of public and private endpoints, then my proposal
wouldn’t pose an improvement. But I think in practice, my scenario of
having many secured controllers/endpoints vs a small number of public
endpoints is a common enough scenario where there would be value to offer
an easier way to support that use case.

The alternative of breaking apart our already established API to conform to
this pattern is development work that’s hard to justify with management at
most organizations.

**Comment by mharrisn** [comment]
I didn't see your full response from my phone when I responded earlier. I think support for a both a uriMatcher function and regex would be perfect additions. If only one change is made, I'd give higher priority to the uriMatcher function. I certainly understand the hesitancy to add complexity to the SDK, but I believe the benefits to consumers of the SDK warrant it in this case. If the goal for this SDK is to help developers deliver quality solutions as quickly as possible, exclusion logic is absolutely just as important as inclusion logic.
