### ISSUE TITLE
Refresh token issue 

### ISSUE THREAD

**Issue by iotaweb** [auth0/auth0-angular#120]
Hello, 

I encountered a problem recently with tokens not being refreshed if the refresh token was saved in the `auth.signin` callback as opposed to using the `authProvider.on('loginSuccess',...)` callback as shown in the refresh-token example, e.g.

This works:
```
  authProvider.on('loginSuccess', function($location, profilePromise, idToken, refreshToken, store) {
    $location.path('/');
    store.set('token', idToken);
    store.set('refreshToken', refreshToken);
    profilePromise.then(function(profile) {
      store.set('profile', profile);
    });
  });
```
This doesn't:
```
  $scope.login = function() {
    auth.signin({
      authParams: {
        scope: 'openid offline_access'
      }
    }, function (profile, idToken, refreshToken) {
        store.set('token', idToken);
        store.set('refreshToken', refreshToken);
        store.set('profile', profile);      
    });
  }
```
When I try the last method, a refresh token gets saved to the local store, but it is shorter than the one saved id using the  `authProvider.on('loginSuccess',...)` callback.

The error returned from auth0 when using this shorter refresh token is:
```
{"error":"invalid_refresh_token","error_description":"specified refresh_token does not exist","statusCode":401}
```
I've got it working using the method specified in the example (thanks for this), but am curious as to why it doesn't work when saved using the other method. Is this a bug, or am I missing something?

Cheers, Rob

**Comment by mgonto** [comment]
Hey @iotaweb,

How are you?

They work difference because the `loginSuccess` function is called via `$injector.inject` and the other one is just a regular callback.

When you call a function using `$injector.inject`, all the parameters are injected by name. That means that I can do the following and they both work:

````js
function injected(myService, myToken) {
  myService.send(myToken);
}

// Option 2. Parameter order change
function injected(myToken, myService) {
  myService.send(myToken);
}
````

That means in your case that you can put `refreshToken` wherever you want with that name and it'll be injected correctly. We're doing this because you're using the `loginSuccess` function on the `config` method. By default, that means that you can only inject providers. However, this way, you can also inject services to that function like `store` which you're doing in your example :).

When using the callback in the signin method, we're using a regular function. That means that parameter order matters. I've just updated the README to show the order of the parameters in the success callback, but it looks like this: `function(profile, idToken, accessToken, state, refreshToken)`. If you use that signature, once you save `refreshToken`, you'll be saving the correct one!

Does this help?

Cheers!

**Comment by iotaweb** [comment]
Hi Martin,
Thanks so much for your answer and explanation - it helps a lot! I appreciate your updating the documentation :)
Cheers, Rob!

**Comment by theopak** [comment]
Just to follow up since this is the top (and only) google result for that exact Auth0 error message: There are other things that could be going wrong if what Martin specified didn't fix your problem. 

When I got the error `specified refresh_token does not exist`, the problem was that the refresh_token in my request was for a different client_id than the one that was being targeted.
