### ISSUE TITLE
Allow auth0 to work in iOS browsers without enabling "Allow Cross-Website Tracking"

### ISSUE THREAD

**Issue by mayhew3** [auth0/auth0-angular#132]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I've just spent a couple days bashing my head against the wall over why my auth0 app worked on PC, Mac, and Android phones, but not in any browser in iOS. The login works correctly, but it was unable to call my APIs, and get a message from error$ saying 'Login Required'. When I read more about how the httpInterceptor worked by silently logging in using cookies, I looked a bit more into cookie management in iOS browsers, and found that it worked when I enabled the "Allow Cross-Website Tracking" in each browser's settings. I don't know too much about what kind of cookies qualify to be blocked by this setting, but it's certainly not ideal to have to tell the audience for my site to enable this setting just to be able to access it.

### Describe the ideal solution

> A clear and concise description of what you want to happen.

I don't have a concise plan of action, but the hope is that I can use the httpInterceptor in my site without enabling the Allow Cross-Website Tracking setting in my iOS browser.

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

The current workaround is to enable this setting.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by frederikprijck** [comment]
Hey @mayhew3 ,

This behavior is explained in our FAQ at https://github.com/auth0/auth0-angular/blob/master/FAQ.md#1-user-is-not-logged-in-after-page-refresh, including two workarounds (Refresh Tokens or Custom Domains).

> In this case Silent Authentication will not work because it relies on a hidden iframe being logged in to a different domain (usually auth0.com) and browsers with ITP do not allow third-party (eg iframed) cookies. There are 2 workarounds for this using Rotating Refresh Tokens or Custom Domains

Also, this SDK is a thin wrapper around our [SPA-JS SDK](https://github.com/auth0/auth0-spa-js), which also has a FAQ to cover the reason here: https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md

> When not using refresh tokens, the SDK relies on third-party cookie support to log in silently. If you're not using refresh tokens, you could be using a browser that blocks third-party cookies by default (Safari, Brave, etc)

When not using Refresh Tokens, this SDK relies on Third Party cookies which are blocked by Safari, but also Chrome incognito, and soon by Firefox and probably also by Chrome outside of Incognito. There is not much we can do about that from an SDK perspective other than recommending you to use refresh tokens if you need to support Safari.

As mentioned in the FAQ, another solution could be to [set up custom domains](https://auth0.com/docs/custom-domains), in that case the cookies are not considered third party anymore and you should be able to use it on Safari without enabling Refresh Tokens.
