### ISSUE TITLE
Question about a possible improvement on the logout call

### ISSUE THREAD

**Issue by code0wl** [auth0/auth0-angular#165]
Is it possible to make the auth SDK logout call an observable or a promise?
At the moment my app is very reactive and when the user logs out. There is always time delay until the logout call is completed. 

It would be good to hook up this async call into a stream and perform actions based on completion or even errors by having either an observable or promise api.

What do you think? :)

**Comment by frederikprijck** [comment]
Hi,

That would make no sense to do so as the call to `logout` is entirely synchronous, there is no asynchronity involved here, see https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L832

The only thing the SDK does is:

- Clear the cache to get rid of the Tokens
- Redirect to Auth0's logout URL when not setting `localOnly` to `true`.

> There is always time delay until the logout call is completed.

I am not sure I understand what you mean here.
Logging out does not involve an HTTP call that is triggered from your application, instead it involves an actual redirect. So any Promise or Observable you try to use here would be lost anyway because you are leaving your application.
