### ISSUE TITLE
Not authenticated after browser refresh on iOS

### ISSUE THREAD

**Issue by anschm** [auth0/auth0-angular#191]
### Describe the problem

I am running an angular application with Auth0 version 1.6.0. I open the website with the safari browser on my iphone. If I refresh the  safari after login the authentication is gone and I have to login again. If I do the login again by using the method loginWithRedirect the authentication is done with the information from memory (the login page does not appear again). The behavior can also reproduced with the iPhone simulator on mac.

### What was the expected behavior?

After browser refresh the authentication is present like Chrome and Firefox or Safari on Mac. 

### Reproduction

1. Start angular application
2. Open Safari on iOS with iPhone or Simulator
3. Do login with method: loginWithRedirect => isAuthenticated = true
4. Refresh browser => isAuthenticated = false

### Environment

- iOs 14.4
- Auth0 1.6.0
- Angular 12.2.0

**Comment by frederikprijck** [comment]
This is a known issue with Safari and is explained in our FAQ, have a look at https://github.com/auth0/auth0-angular/blob/master/FAQ.md#1-user-is-not-logged-in-after-page-refresh.

**Comment by anschm** [comment]
I figured out that the option localstorage as cache location for the token also fixed the issues. I tried to rotate the refresh token and this doesn 't fixed the problem. How critical is it to use the localstorage as cache location?

**Comment by frederikprijck** [comment]
> How critical is it to use the localstorage as cache location?

Not sure what u mean. As mentioned in the FAQ, you can solve the problem without local storage, but using Custom Domains.

**Comment by anschm** [comment]
I dont know. Maybe my problem is another one and not like whats descripted in the FAQ. But actually to use the localstorage as cachelocation solved it well. Anyway I try custom domains today. But with Safari on Mac all is going well, also if I use memory as cachelocation. The problem only appears on ios.

Are there any disadvantage to use the localstorage as cachelocation?

**Comment by frederikprijck** [comment]
When using cachelocation localstorage, the problem is solved on page refresh but once your Access Token expires, your user will be logged out again. This is solved by using Refresh Tokens together with Local Storage.

There certainly are disadvantages to using localstorage, which is why we default to using in-memory.
The main concern is being subject to XSS attacks. However, when u use Rotating Refresh Tokens, you are lowering the risk.

However there are also benefits to using Local Storage, so it's a decision one has to make for its own, depending on their use-case (e.g. supporting Safari without being able to use Custom Domains might be one reason to use local storage).
