### ISSUE TITLE
`singout` does not logout from auth0

### ISSUE THREAD

**Issue by ashishtilara** [auth0/auth0-angular#223]
According to source, `signout` doesn't really logout from Auth0 (just unsets variables on device), so if someone gets hold of token from http-request, token still be valid inside application. Is is possible to add new logout mechanism you recently suggested (https://auth0.com/docs/logout) into this module too?

**Comment by bwinchester** [comment]
Here is a hidden iframe implementation of their suggestion of opening a window and visiting the logout url in the user's browser. It combines your url about their logout suggestion and the default logout example they provide. It avoids needing to redirect to logout url and also avoids a new tab or blank window. Replace [appName] with your auth0 app name. I tried to AJAX the logout url, but it wasn't deleting the cookies because my app is obviously not the same domain as auth0. That's why this is an iframe. This logout method ensures if they click logout, they don't come back in the same browser and have the ability to pickup an unexpired token and login without authenticating again. 

`function logout() {
          var logoutIframe = window.document.createElement("iframe");
          logoutIframe.setAttribute('style','display:none;')
          logoutIframe.setAttribute('src','https://[appName].auth0.com/v2/logout');
          window.document.body.appendChild(logoutIframe);
          store.remove('profile');
          store.remove('token');
          resetProfileNull();
          auth.signout();
        };`

**Comment by mpaul31** [comment]
i do not see you redirecting anywhere (within your current app) after the user logs out. are you doing this elsewhere (ssoLogout event) ?

**Comment by bwinchester** [comment]
@mpaul31, you can add a redirect functionality after the logout function. I don't have a redirect on logout because auth0-angular adds some functionality to angular's router. I predefine which routes need authentication to view, and when you logout, it goes to a default route.

**Comment by mpaul31** [comment]
@bwinchester that is actually what i do. my custom directive simply calls auth.signout() and i have an event listener that handles the logout event and performs session clean-up and redirects. i was just confused because this is all the angular auth0 code does on signout and your code does not show any state changes:

```
                auth.signout = function () {
                    auth.isAuthenticated = false;
                    auth.profile = null;
                    auth.profilePromise = null;
                    auth.idToken = null;
                    auth.state = null;
                    auth.accessToken = null;
                    auth.tokenPayload = null;
                    callHandler('logout');
                };
```

**Comment by bwinchester** [comment]
Yeah, The router event listeners for auth0 handle that and redirect to a default page.

**Comment by christiannwamba** [comment]
Just like `loginSuccess` and `loginFailure`, there is a `logout` event which is called when `auth.signout` is called. You can handle all your logout logic in that event handler.

**Comment by christiannwamba** [comment]
Hi! Will be closing this issue but feel free to re-open if you need more help

**Comment by kim0z** [comment]
@ashishtilara Hi, I have the same issue, the signout works in local, but I don't see the signout window, and the auth0 service doesn't updated in the history that I was logged out, did you find a solution?

**Comment by ashishtilara** [comment]
@kim0z the only way I can think of doing it is logout request goes to `<account>.auth0.com/v2/logout` as well as send to server which then adds the token in blacklist, and on login, and other requests, you first check the blacklist and if it exist in there deny access. does it make sense?

**Comment by divinentd** [comment]
I am also running into the problem where logging out via `mydomain.auth0.com/v2/logout` does not log you out from auth0.com, so that if someone gets ahold of the token it may still be valid.

I like the proposed blacklist solution, but the company has a desire to keep all of the authentication work within Auth0.

Another solution that has been proposed is to shorten the life of the JWT, and use a Refresh Token to renew it in the background. The advantage being that Refresh Tokens can be revoked when the user logs out.

What do you think?
