### ISSUE TITLE
Support for non-default audience

### ISSUE THREAD

**Issue by jmac105** [auth0/auth0-angular#225]
### Describe the problem you'd like to have solved

We’re struggling with the lack of support for non default audiences in auth0-angular. On auth0-spa-js it’s possible to pass audience as a parameter to methods on the authClient such as getUser & getIdTokenClaims, however this is not possible in auth0-angular which is causing us some headaches.
If the user has a token but not for the default audience it’s not possible to see the idToken values on the user$ observable, instead we’re having to make a call to our API to look up the details on the management api and return that instead which is not efficient.

### Describe the ideal solution

> A clear and concise description of what you want to happen.

We think this would be solved if auth0-angular exposed the underlying auth0-spa-js authClient instance so that we can use the methods on that directly. Aside from that happening is there any way that we can accomplish what we need with the existing auth0-angular package?

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

We understand there's some solution possible via injection tokens but not sure hot to achieve this. Ideally the angular package would export the authClient instance it creates rather than us having to inject a client instance which would need us to have a dependency on both the auth0-angular package and the auth0-spa-js package

This follows on from https://community.auth0.com/t/support-for-non-default-audience-in-auth0-angular/70619

**Comment by frederikprijck** [comment]
Hi,

Ideally, I would love for this to be supported in our SDK in a more Angular way. But for now it is already possible.

> Ideally the angular package would export the authClient instance it creates rather than us having to inject a client instance which would need us to have a dependency on both the auth0-angular package and the auth0-spa-js package

I am a bit confused tho. U are asking if there is a way to get access to the Auth0Client, but you do not want to inject it.
Also, installing `auth0-angular` will pull in `auth0-spa-js`, so there is no explicit need to add an extra dependency (u already have that dependency implicitly). But even then, if u want to access the Auth0Client instance (which is part of Auth0-SPA-JS), adding a dependency to `Auth0-SPA-JS` seems fair to me. This is not a common use-case (it has been brought up twice) and not impossible with today's SDK, just not ideal (see https://github.com/auth0/auth0-angular/issues/214#issuecomment-917295461) .

I am happy to review a PR that implements this in a non-breaking way, but given it's already possible it's not something we have a short-term plan for to prioritize.

Thanks.

**Comment by jmac105** [comment]
@frederikprijck I'm confused why was the functionality added in #276 removed in v2 of this package?

**Comment by frederikprijck** [comment]
That got removed from SPA-JS because in an application, there should realy only be one user. If the user interacts with multiple API's and use multiple audiences, it should still be one user.

Therefore, the underlying SDK got reworked in such a way to remove the concept of getting user and idTokenClaims by audience and scope, instead there is only ever one user and claims.

User and claims should not be dependent on the audience being used as an id token and an audience are unrelated to eachother. Audiences should only impact the access token, not the id token.

As a result of that, we also removed it from v2 of this SDK, as well as auth0-react and auth0-vue.

**Comment by frederikprijck** [comment]
To add to that, if you have extensions (rules, actions) that add claims to the id token based on the audience provided, I would argue that isn't something someone should do. Instead, you should add it to the access token.

If you then need to use these values in client, you need to ensure every API exposes an endpoint that returns these values from their own access token respectively, and not (mis)-use an id token for it, just because it's easier (because it's not, as we shouldnt have had support for this from the beginning anyway).

I know this causes more roundtrips in an application, but that would be the consequence of using multiple audiences in one application (it also causes more roundtrips to auth0 when u use multiple audiences). In general, I would encourage trying to limit audiences used in a single application, one way would be to look into the concept of [Logical API's](https://auth0.com/docs/get-started/apis/set-logical-api).
