### ISSUE TITLE
Add Cypress example that tests the login

### ISSUE THREAD

**Issue by nekkon** [auth0/auth0-angular#291]
Hello, I have followed examples and articles from many different sources but without success. It seems they are now outdated and not sure which way to silently login in order to run Cypress tests.

The last approach I followed is:

`const username = Cypress.env('E2E_USERNAME');
      const password = Cypress.env('E2E_PASSWORD');
      const audience = Cypress.env('E2E_AUDIENCE');
      const url = Cypress.env('E2E_OAUTH_URL');
      const client_secret = Cypress.env('E2E_CLIENT_SECRET');
      const client_id = Cypress.env('E2E_CLIENT_ID');
      const scope = 'openid profile email';

      const body = {
        grant_type: 'password',
        username,
        password,
        audience,
        scope,
        client_id,
        client_secret,
      };

      const options = {
        method: 'POST',
        headers: {},
        url,
        body,
      };

      cy.request(options).then(response => {
        const baseUrl = 'http://localhost:4200';
        const appState = { state: 'any-state' };
        const visitUrl = 'callback';
        const { access_token, expires_in, id_token, token_type } = response.body;
        const expireDate = Math.floor(Date.now() / 1000) + expires_in;

        cy.window().then(win => {
          win.sessionStorage.setItem(
            `a0.spajs.txs.${client_id}`,
            JSON.stringify({
              code_verifier: 'any-code',
              appState,
              scope,
              audience,
              redirect_uri: baseUrl,
            }),
          );

          win.localStorage.setItem(
            `@@auth0spajs@@::${client_id}::${audience}::${scope}`, // Could also be ::default:: instead of ::${audience}::
            JSON.stringify({
              body: {
                client_id,
                access_token,
                id_token,
                scope,
                expires_in,
                token_type,
                decodedToken: { user: JSON.parse(Buffer.from(id_token.split('.')[1], 'base64').toString('ascii')) },
                audience,
              },
              expiresAt: expireDate,
            }),
          );

          cy.intercept('POST', '/oauth/token', {
            body: {
              access_token,
              id_token,
              scope,
              expires_in,
              token_type,
            },
          });
        });

        cy.visit(`${visitUrl}/?code=test-code&state=any-state`);`

Any suggestion or idea to make this work? Would be great to add an example in this repo similar to this one and test signIn with auth0 using an AuthGuard. Seems a lot of people in the community are having the same issue. Would be great to also keep it up to date and part of the documentation.

**Comment by frederikprijck** [comment]
Hey,

We have our own playground application inside this repository that we use to both manually test things, but also run a couple of e2e tests against, which also uses Cypress.

You can look at it here: https://github.com/auth0/auth0-angular/blob/e9b216bc679ef16ada09b78f81e1a6fedcd0c2ee/projects/playground/e2e/integration/playground.spec.ts

Note, on master you will notice this file is different, as we are now running our e2e tests against a mock OIDC provider, and not against Auth0. But the link above points back in history to show you how our e2e tests used to work with Cypress and our SDK when it was still targetting Auth0.

Looking at master can also help to give you an idea of how you can use our SDK to target your own mocked OIDC provider to run your e2e tests against instead of Auth0. But that does come with some additional complexity in setting that OIDC provider up for testing.

Would that help? Let me know if something isn't clear in those tests.

**Comment by roldengarm** [comment]
@frederikprijck  I had the same issue. Your approach works, but it depends on the Auth0 UI; i.e. if the HTML classes in the login form change, the e2e tests will break.
On [your main blog post about this](https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/), you literally say: **The best practice is never to visit or test third-party sites over which you have no control.**

So this goes exactly against it. 

I've searched for other solutions, but most of them involve setting local storage / cookies, and it didn't work for me in the end. It would also depend on e.g. setting cache to session instead of memory (default setting).

**Comment by frederikprijck** [comment]
I would say if that's a concern, you can always look into using a mocked OIDC server in the same way we are doing.

Knowing how our SDK works internally, I believe it won't be easy to configure it in such a way that it doesnt redirect you to either Auth0 or a mocked OIDC server.

The blog post you linked isn't about our Angular SDK, it involves our older Auth0-js SDK, which we do not encourage to use in Single Page Applications. Using Auth0-JS, the library discussed in that blog post, it will be easier to bypass the login screen. But I do not believe it's a good idea to give in on security best practises (as our Angular SDK uses our SPA-SDK, which is tailored specifically for SPA's) only to avoid redirects in e2e tests.

**Comment by nekkon** [comment]
@frederikprijck Thank you for trying to help. I managed to make things work by following the solution in this post's answer. https://stackoverflow.com/questions/67222522/auth0-authentication-with-cypress. I also made the AuthConfig same for the app and the Cypress e2e tests, as that was the reason things weren't working for me. Although a hackish way of doing things, this was the quickest way to setup the e2e tests based on how things are configured atm. Might follow your suggestion for having a mocked OIDC server if I find time.

**Comment by frederikprijck** [comment]
Keep in mind that, when talking about relying on third party services for your tests, I believe it's less of a problem to rely on our Login Page as it is to rely on the internal structure of how we store things in local storage.

This approach bypasses everything in our SDK and assumes everything works fine when u put a token in the correct place in localstorage.
Keep in mind, there is nothing that guarantees our SDK does work correctly like this, neither is there any guarantee that it will continue to work in the future.

Our SDK only supports redirect based flows (or popup, but that gets close to redirects but in a popup). Trying to do anything differently with your tests will always be risky and have no guarantees.

Even though I see how that stackoverflow answer works, that's not what we recommend. I would still encourage you to look at how we write our own tests. Our SPA-JS, Angular and React SDK all use Cypress.

Whether or not you use a mocked OIDC server is another discussion.
