### ISSUE TITLE
Remove provideIn: root from AuthService

### ISSUE THREAD

**Issue by DaSchTour** [auth0/auth0-angular#297]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> AuthService is provides globally. This doesn't allow to inject AuthService with `@Optional()` to avoid issues within SSR.

### Describe the ideal solution

> AuthService is only available if AuthModule is imported

## Alternatives and current work-arounds

> There is no workaround

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by frederikprijck** [comment]
Can you elaborate a bit more here?
I just reached out to the person on the Angular team who actually inmplemented `providedIn: 'root'` in the framework, and he can't see why providedIn root would need to be dropped to support the [guard pattern](https://github.com/angular/universal/blob/master/docs/gotchas.md#strategy-2-guards) for Angular Universal.

The conversation between myself and the Angular team can be found here: https://discord.com/channels/748677963142135818/749343618128412751/954304423604154389

I am more than happy to try improve anything we can to use Angular Universal, but I believe dropping `providedIn: 'root'` isn't what we need to be doing.

**Comment by DaSchTour** [comment]
Well. I use a bit different pattern. I have a separate `app-browser.module.ts` which is included only in browser context. In this `app-browser.module.ts` I import the `AuthModule`. In my components in import AuthService with `@Optional()` but in server context it's still injected but doesn't work because because `Auth0ClientService` is not available. So it actually doesn't make any sense to have `providedIn: 'root'` on AuthService as it will not work without `AuthModule` and `Auth0ClientService`. And `AuthService` is also provided in `AuthModule` so I don't see any benefit in having `providedIn: 'root'` but it doesn't allow to "exclude" by not importing `AuthModule` in a certain context.

My current workaround is it add `{provide: AuthService, useValue: {}}` in my `app-server.module` but that's pretty ugly solution.

**Comment by DaSchTour** [comment]
I would simply expect this to work and not throw an error: https://stackblitz.com/edit/angular-ivy-xpb9ee?file=src/app/app.component.ts

**Comment by frederikprijck** [comment]
I am not sure I follow this. Our SDK is not supposed to work if you don't provide certain parts of it. Leaving out some crucial part of it isn't something that will work (unless you provide a dummy service as you are doing).

I also think that it's recommended to use the approach documented by the Angular team, which is both to use providedIn root for pretty much all use cases, as well as use the guard pattern for Angular Universal, which I believe is exactly what you are doing here.

I don't believe we should drop providedIn root, which would not be an improvement for the majority of our users, when you have a workaround, which I believe is exactly what is being mentioned in the docs on how you should solve this.

> My current workaround is it add {provide: AuthService, useValue: {}} in my app-server.module but that's pretty ugly solution.

I don't agree this is an ugly solution given it is in line with what is being mentioned in the link. As you can see here, the official solution is to add a provider in the server platform to avoid using our SDK, which is exactly what you are doing.

I believe there isn't much we can do here. I am always open for feedback on how we can improve but I am closing this for now.

**Comment by DaSchTour** [comment]
Well the point is. The majority of users shouldn't even notice the change. As like I stated AuthService is provided through the module. And from my point of view a service should not be provided in root if it is not self-sufficient, which the AuthService is not as it depends on `AuthModule` and `Auth0ClientService` but setting it to provide in root is like saying you can use it in root without and additional dependencies.

So removing this will not changing anything for majority of users but would make it easier for scenarios in which `AuthService` might be optional. Another use case might be to have a library with components that can use AuthService but can also work without. In this case you might want to inject AuthService with `@Optional()`. But you can't. You will have to provide the hack into all modules that use this component.

Imagine having a project with 100 apps. 20% of them user Auth0 and 80% do not. You have a library with shared components that have some special behavior if `AuthService` is available. Normally you would inject `AuthService` with `@Optional()`. But that doesn't work with a service that has `provideIn: 'root'`. So you have to add the provide hack to all 80 projects that actually don't have any dependency to Auth0.

So I really don't understand why improving and extending the possibilities without harming the usage for other users is such a problem?

**Comment by frederikprijck** [comment]
I believe we are focussing on a solution rather than a problem.

Our SDK is not supposed to be used without importing `AuthModule.forRoot()` in the root of your project. That's a common practice in Angular.
Injecting `AuthService` without importing `AuthModule.forRoot()` will fail as you can see in your provided StackBlitz.

There are two possible ways we can solve this:

- We can rework the SDK in such a way that it won't throw the error, we can do this by either making some dependencies on AuthService optional, while keeping `providedIn: root`. Or by dropping `providedIn: 'root'` on AuthService.

- Or whenever someone decides they need our Service on a different platform such as Angular Universal, they can leverage the pattern recommended by the Angular Team.

The downside of the first solution (while keeping providedIn root) is that you have no control over what's happening in the service on the server. Our SDK doesn't work on the server because of the usage of Window, so there might be other issues.  On top of that, we will need to add additional warnings to tell our users they are using our AuthService without registering `AuthModule.forRoot()`, and it won't function as expected.

We can ofcourse drop the providedIn root, which doesn't have the above issues. However, I believe providedIn root should only be dropped when it's not possible to use it (which are very rare cases).  Because Angular can optimize services that use `providedIn: 'root'` internally, I'd be keener on marking dependencies optional instead, but only when there would be a need for doing so, which I believe there isn't. Our depdencies aren't optional and our service can not work without those dependencies. If you need a `Mock` version for our SDK, mock it like you mock any other service in Angular (`{provide: AuthService, useValue: {}}`)

> So I really don't understand why improving and extending the possibilities without harming the usage for other users is such a problem?

All of the above are downsides for other people, while I believe there is no need for any change as you can already leverage the Guard pattern with the current version of our SDK, making our SDK work perfectly fine using Angular Universal. 

I understand you believe this isn't ideal, but it is  following the best practises by the Angular team, being: Use providedIn: root unless not possible, as well as use the Guard pattern for situations like this.

If you believe you have no way to get our SDK working using Angular Universal, I am happy to reopen and revisit this. But as far as I can tell, everything works fine using the documented approaches.

> Well the point is. The majority of users shouldn't even notice the change.

I believe dropping `providedIn: root` could be a breaking change. But anyone using `AuthModule.forRoot()` incorrectly (e.g. importing it in a Lazy Loaded Module), would suddenly get two instances of AuthService while previously this might have always been a single instance.

Even tho I would argue the above is incorrect usage of our SDK (forRoot should never be imported elsewhere but in the AppModule) and not an actual situation we should support or consider when talking about breaking changes, I am also not keen on breaking them just for the sake of breaking them as I believe our SDK still works fine.

That said, I don't believe the above is a reason to decide whether we should or shouldn't change this. If we need to make a change in our SDK to make our SDK work with Angular Universal, we would.

> Imagine having a project with 100 apps. 20% of them user Auth0 and 80% do not. You have a library with shared components that have some special behavior if AuthService is available. Normally you would inject AuthService with @Optional(). But that doesn't work with a service that has provideIn: 'root'. So you have to add the provide hack to all 80 projects that actually don't have any dependency to Auth0.

In applications of that size, it's not uncommon to provide an abstraction on top of a third party service that should allow for just that. I am not convinced putting an Auth0 dependency on all your Shared Components is a good idea to begin with.

Here is a reworked version of your initial stackblitz using the above wrapping service: https://stackblitz.com/edit/angular-ivy-4pkzqw

If you don't need to use Auth0, don't provide `MyAuthService`. If u need to use Auth0, provide `MyAuthService` but also ensure u import `AuthModule.forRoot()`

I do not believe this is what you need in this specific use-case, but I do believe this is a solution for people that have a situation that you are explaining as well. This is a pattern beyond our SDK and works with any third party library.

> So you have to add the provide hack to all 80 projects

I understand you are not in favor of that approach, but this isn't a hack in the use-case of Angular Universal. This is [the documented approach](https://github.com/angular/universal/blob/master/docs/gotchas.md#strategy-2-guards) that people are expected to use when they can't use a specific implementation on a specific platform.
Regarding the situation with 100apps, I believe there are other solutions as elaborated.
