### ISSUE TITLE
auth.user$ emits infinitely when combined with RxJS pipe and AsyncPipe

### ISSUE THREAD

**Issue by Coffettaja** [auth0/auth0-angular#319]
### Describe the problem

Using RxJS pipe on `auth.user$` and then providing `auth.user$` to Angular's AsyncPipe causes the `auth.user$` to emit infinitely.

### Background and details

In our application, we have created a separate service that uses the AuthService. We do this so that the data from `user$` matches the data format that our components are expecting. Our service redefines `user$` as follows:

```typescript
class CustomAuth {
  constructor(private auth: AuthService) {}

  transformUser(user) {
    // some logic here
  }  

  get user$() {
    return this.auth.user$.pipe(
      distinctUntilChanged((prev, curr) => _.isEqual(prev, curr)),
      map(this.transformUser)
    )
  }
}
```

This is then used in an html template: 

```html
<div *ngIf="(customAuth.user$ | async) as user">
</div>
```

This causes the `auth.user$` to emit continuously, even with `distinctUntilChanged(() => true)`.
This seems to happen when any RxJS operators are provided to `.pipe()`. If nothing is added to `.pipe()`, no inifite loop occurs.

Interestingly this does not occur if the `customAuth.user$` is redefined on the component, and that local variable is used in the template so this is used as a workaround for now:

```typescript
class SomeComponent implements OnInit {
  constructor(protected customAuth: CustomAuth) {}

  ngOnInit() {
    this.user$ = this.customAuth.user$
  }
}
```
```html
<div *ngIf="(user$ | async) as user">
</div>
```

### What was the expected behavior?

`auth.user$` would emit the same amount as normal even when adding `.pipe()` to the observable when used with AsyncPipe.

### Reproduction

Create a service that re-exports `auth.user$` with any `.pipe` operators attached. Use this new `user$` with AsyncPipe in an html template.

Possibly related:
https://community.auth0.com/t/infinite-requests-when-piping-auth-user-in-angular-auth-o/57136

### Environment

- **Version of `auth0-angular` used:** 1.9.0
- **Which browsers have you tested in?** Chrome, Firefox

**Comment by frederikprijck** [comment]
Thanks for reaching out, the reason this is happening is because you are using a getter on your CustomAuth service.

Replacing your service with the following should solve the problem:

```ts
class CustomAuth {
  constructor(private auth: AuthService) {}

  transformUser(user) {
    // some logic here
  }  

  user$ = this.auth.user$.pipe(
    distinctUntilChanged((prev, curr) => _.isEqual(prev, curr)),
    map(this.transformUser)
  );
}
```

What's happening is the following:

- Whenever u use an rxjs operator (inside `.pipe()`), rxjs creates a new observable.
- In TypeScript, when u use a getter, whenever u access the getter it will execute the code inside the getter. In this case, it means that every time you access the getter, a new observable is created, starting with `this.auth.user$`, which is a behavior subject which will always emit the last known user value on the first subscription.
- In Angular, when u access a getter from the HTML, it will execute the code inside the getter every Change Detection run, which can be a lot every second. Therefore, what's happening here is that Angular calls the getter, the getter creates a new observable and emits the last known value of the user.


> Interestingly this does not occur if the customAuth.user$ is redefined on the component

This is also why it is solved when u use a property in your component, because then Angular isn't constantly calling a getter anymore.

This is a problem that is typical to rxjs and not related to our SDK, take the following CustomAuth service:

```ts
class CustomAuth {
  userSubject - new BehaviorSubject({name: 'test'})

  transformUser(user) {
    // some logic here
  }  

  get user$() {
    return this.userSubject.pipe(
      distinctUntilChanged((prev, curr) => _.isEqual(prev, curr)),
      map(this.transformUser)
    )
  }
}
```

The above should have the same behavior as you have initially, which is also solved by avoiding the getter:

```ts
class CustomAuth {
  userSubject - new BehaviorSubject({name: 'test'})

  transformUser(user) {
    // some logic here
  }  

  user$ = this.userSubject.pipe(
    distinctUntilChanged((prev, curr) => _.isEqual(prev, curr)),
    map(this.transformUser)
  )
}
```

Let me know if that helps.

**Comment by Coffettaja** [comment]
You are right, removing the getter solved the issue. Thank you for the explanation. I'm closing the issue.
