### ISSUE TITLE
Manually setting an access token doesn't work via AuthState.setAccessToken(...)

### ISSUE THREAD

**Issue by daniel-maegerli** [auth0/auth0-angular#328]
### Describe the problem

I've implemented a passwordless login (via Angular Http Client) for SMS and E-Mail, which is working so far. I can initiate the passwordless process, request an OTP, verify it and receive the access token. I can even do authenticated http requests with the token. So far so good.

The problem is that this is only working when NOT using the AuthHttpInterceptor of this library. My idea was that I can still use the AuthHttpInterceptor (which takes care of adding authorization headers etc.) and just set the access token manually via AuthState.setAccessToken(...). But this doesn't seem to work, since it will not change the authentication state. 

### What was the expected behavior?

I expect that when setting a (working and tested) access token via AuthState.setAccessToken(...), the auth0-angular library takes that up, refreshes its state to be authenticated. Since this doesn't seem to be working, it is either a bug or the exposed method is missleading somehow.

### Reproduction

1. Create an Angular application (v13) and install @auth0/auth0-angular (v1.10.0)
2. Import AuthModule in the AppModule with the appropriate configuration
3. Integrate AuthHttpInterceptor in the AppModule
4. Try to set an access token via AuthState.setAccessToken(...)
5. Do an HTTP requests towards the provided audience.

### Environment

- Angular v13.2.2
- auth0-angular v1.10.0
- Google Chrome v103

**Comment by frederikprijck** [comment]
Thanks for reporting this.

I don't believe your use-case has ever been supported. The `AuthState` is actually used internally by the SDK to set its state, not for you to try and inject things.

The reason it's failing is because the underlying SDK, Auth0-SPA-JS, does not support providing it with a token, you are supposed to use the SDK to retrieve and manage the token. Same goes for our Angular SDK.

I would recommend not using our SDK based on what you are trying. You should be fine just rolling your own interceptor based on ours.

Apologies for the confusing exposed AuthState, we should properly mark it as intended for internal use.

**Comment by daniel-maegerli** [comment]
Thanks @frederikprijck, got it and will work with a custom interceptor then. I'd support your plan to mark it for internal use.
