### ISSUE TITLE
I think this package need to be rewritten ... really

### ISSUE THREAD

**Issue by Mfron-42** [auth0/auth0-angular#380]
All this logic of redirect could be MUCH simpler and MORE useful. Not even speaking about variables and functions naming...

Ill have to wrap your service into a better one, and to use a routeguard to avoid your redirect system.

https://github.com/auth0/auth0-angular/blob/ee48ce728a5d4e796e706a19cf7659fefe9c542c/projects/auth0-angular/src/lib/auth.service.ts#L103

**Comment by frederikprijck** [comment]
Thanks for reaching out. 

Sorry to hear you feel that way, but please know that we are always open to improving wherever we can, so happy to take a look at any suggestion to simplify things.

Currently, there isn't much to act on with this issue. Keeping this open for now, but would be helpful to elaborate on the potential improvements here.

**Comment by Mfron-42** [comment]
Im sorry but there is many things to change.

First of all, the method name should speak by itself ... checkSessionOrCallback wich is an observable which takes a bool isCallback ...


You are using TOO MUCH observable anywhere, in angular is already a reactive framework, you dont need to work with reactive variables evrywhere.

Store the last user and token, which you will obviously need.

And speaking of, sometimes you are giving an obserble wich give only one value and never update you, even worst, sometimes it never resolves :

firstValueFrom(this.auth.getAccessTokenSilently()); // will never resolve if you are logged out, and then loggin after this.

Expected behaviour :  send you the new value when the value changes.

**Comment by frederikprijck** [comment]
> First of all, the method name should speak by itself ... checkSessionOrCallback wich is an observable which takes a bool isCallback ...

`checkSession` and `callback` are two terms we frequently use internally in all of our SPA SDKs. When the SDK is initialized, we need to either check the session, or handle the callback. I am not entirely sure I understand the bad naming here.

> You are using TOO MUCH observable anywhere, in angular is already a reactive framework, you dont need to work with reactive variables evrywhere.

I understand there are differences in opinions, but I don't consider using observables when integrating with Angular a bad idea. Keep in mind that our SDK is nothing but a tiny wrapper around the [Auth0-SPA-JS SDK](https://github.com/auth0/auth0-spa-js). So the purpose of this SDK is to provide an Angular API on top of Auth0-SPA-JS, levering rxjs. Keep in mind our promise -based Auth0-SPA-JS SDK is always available for people that want to use a Promise based API instead of an Angular one, however it does mean you will need to write your own Guard, Interceptor and Service.

> Store the last user and token, which you will obviously need.

We already store this in a cache inside `Auth0-SPA-JS`, on top of that the last user is available by using the `user$` observable. The internal caching of SPA-JS works in such a way that it can hold multiple tokens in the cache, based on several parameters you can pass to all our methods. So there isn't such thing as "the last token". Instead, you want to call `getAccessTokenSilently`, which will look up in the cache based on the provided arguments and ensures it returns the last one it can find based on those arguments.

> And speaking of, sometimes you are giving an obserble wich give only one value and never update you, even worst, sometimes it never resolves :

> firstValueFrom(this.auth.getAccessTokenSilently()); // will never resolve if you are logged out, and then loggin after this.

I don't think that is the intention of `getAccessTokenSilently`, what you want is to integrate `getAccessTokenSilently` using mergeMap (or concat/switch/exhaustMap): `mergeMap(() => this.auth.getAccessTokenSilently())`
This is a consequence of the fact that we have no true `last known token` and that we have no reactive way to track the tokens. I believe we could do that, but would add even more rxjs, which if I understand correctly isn't what you are looking for.

However, you can solve what you want in user-land by changing:

```ts
firstValueFrom(this.auth.getAccessTokenSilently());
```
to
```ts
this.auth.isAuthenticated$.pipe(
  filter(isAuthenticated => !!isAuthenticated),
  switchMap(() => this.auth.getAccessTokenSilently())
)
```
With the below code, if the user is logged out, logging in will result in the call to `getAccessTokenSilently` to be kicked-of. On top of that, instead of moving back to Promises, we stick to Observables which typically is a good idea in Angular.

If you do wish to use the Promise, you should be able to use:

```ts
firstValueFrom(this.auth.isAuthenticated$.pipe(
  filter(isAuthenticated => !!isAuthenticated),
  switchMap(() => this.auth.getAccessTokenSilently())
))
```

Would that help?

**Comment by Mfron-42** [comment]
Hi, thank you for your answer.

This snipet is not solving the same probleme since i dont want to use it as observable, because the code will become harder to read. I already changed it to :


```
export class AuthService {

  private currentUser : User | undefined;

  constructor(public auth: Auth0) {
    auth.user$.subscribe(user => {
      this.currentUser = user || undefined;
    });
  }

  public get user() : User | undefined {
    return this.currentUser;
  }

  public getToken() : Promise<string> {
    if (!this.user)
      return Promise.resolve(undefined as any as string);
    return firstValueFrom(this.auth.getAccessTokenSilently());
  }

  public login() : void {
    const target = window.location.href.replace(window.location.origin, "")
    this.auth.loginWithRedirect({
      appState: { target },
    });
  }

  public logout() : void {
    this.auth.logout({localOnly: true});
  }
}
```

There is someting to tell too, is that the redirect with the app state is used from root, so you need to inject an instance of your service to the root, so it can trigger the redirect, without this the redirection wont work

**Comment by Mfron-42** [comment]
making it this way, make the code simpler and faster

```
<p>offers works!</p>
<ng-container *ngIf="auth.user; else loggedOut">
    <button (click)="logout()">
        Log out
    </button>
</ng-container>

<ng-template #loggedOut>
    <button (click)="login()">Log in</button>
</ng-template>

<ul *ngIf="auth.user">
    <li>{{ auth.user.name }}</li>
    <li>{{ auth.user.email }}</li>
</ul>

```

**Comment by frederikprijck** [comment]
Thanks for sharing those snippets. I believe that if you prefer avoiding an Observable based based API, a service like you are using makes sense.

However, the [HTML used](https://github.com/auth0/auth0-angular/issues/380#issuecomment-1319891882) can be achieved identically (apart from the fact that it needs one addition, being using the [`async` pipe](https://angular.io/api/common/AsyncPipe) on the `user$` observable.) without making any change to our SDK, and without wrapping the SDK's AuthService in your own Service, so I am not entirely sure what you mean with it making it simpler and faster.

I am also still not sure what's so bad about this SDK if all you need is a tiny wrapper like you have shared to make it suit your needs.

I believe it's perfectly fine for someone to not enjoy working with rxjs, but as Angular integrates heavily with Observables, it makes more sense to offer rxjs integration by default and have people that prefer not to use an Observable based API wrap it with their own service. On top of that, Angular's Guards and Interceptors both integrate very well with Observables, which are the core parts of this SDK.

> There is someting to tell too, is that the redirect with the app state is used from root, so you need to inject an instance of your service to the root, so it can trigger the redirect, without this the redirection wont work

Can you tell a little bit more about your set up, as well as what happens if you do not inject it? I would be happy to look into that and see if it's anything we can fix.

**Comment by Mfron-42** [comment]
https://github.com/auth0/auth0-angular/blob/ee48ce728a5d4e796e706a19cf7659fefe9c542c/projects/auth0-angular/src/lib/auth.service.ts#L93

Here you are checking to apply the redirection, using appState, but if the contructor is not called, the redirection wont be called obviously.

So, if you dont need the auth service at the origin of your project, you wont call this code wich wont redirect you. You have to create an instance of this to enable the redirection, by simply inject it in your AppComponent for example, even if you dont need it

**Comment by frederikprijck** [comment]
Thanks, I believe I understand where you are going, will try and reproduce this and have a look at what can be done about that.

I believe for situations like this, we might need an explicit `initialization` method on the `AuthService`, which you would still need to call in the AppComponent for example. However, will see if there is anything else that can be done about that.

**Comment by Mfron-42** [comment]
It took my 4 hours to check why your sdk redirect me everytime, sometimes not, sometimes the observable is not providing any new value, i have to write a service to access to the last data. I mean im sorry, but its one of the worst sdk i used. And if there is a simpler sdk wich could provide me the same service faster, i wonder why i couldnt find it in the documentation.

Im realy sorry, but i had to share my opinion, its only mine and if all others users are happy to use it as it is, i guess its fine

**Comment by Mfron-42** [comment]
> Thanks, I believe I understand where you are going, will try and reproduce this and have a look at what can be done about that.
> 
> I believe for situations like this, we might need an explicit `initialization` method on the `AuthService`, which you would still need to call in the AppComponent for example. However, will see if there is anything else that can be done about that.

Yes, could be an answer, but understand that the redirect problem + the different error + the doc + the variable missing in the service, i had to read your package to solve my issues

**Comment by Mfron-42** [comment]
The 'different error' is : i cannot add redirect uri to /product/45, since its a generated name, so i have to use appstate, i had the redirect problem with the uninitialized sdk, and i tried loginwithpopup wich serve me your error page without additional information. wasnt a good experience.

**Comment by Mfron-42** [comment]
I got the token, everything works as expected, i tried to send a the token to my server usint the header Authorization : Bearer <TOKEN> it doesnt work, so i try using your version : https://auth0.com/docs/libraries/auth0-angular-spa

```
    this.http.get("API_ROUTE").subscribe(res => {
      this.callResult = JSON.stringify(res);
    });
```

This make a call to get the token, and without any error anywhere, it doesnt follow with my request to API_ROUTE, ill have to read your package and debug again since there is no error/information

**Comment by Mfron-42** [comment]
I think i used the wrong audience/  scope, so the observable never publish any value, and i wont get any error  or information

**Comment by frederikprijck** [comment]
> Yes, could be an answer, but understand that the redirect problem + the different error + the doc + the variable missing in the service, i had to read your package to solve my issues

I can see how an issue like the one with injecting the `AuthService` can be hard to debug, I would say it's expected that if you don't inject any of our artifacts, it won't be instantiated, as that's how Angular DI works. However, I do understand this shouldn't be something you have to debug yourself, and should be clear in the documentation or avoided altogether to begin with.

> It took my 4 hours to check why your sdk redirect me everytime, sometimes not, sometimes the observable is not providing any new value, i have to write a service to access to the last data

I am not sure what's causing that, but I can't really help without seeing the actual code. Please feel free to open another issue that explains the situation where you aren't getting latest value out of our SDK, as if that's the case it's a bug we should solve.

> The 'different error' is, i cannot add redirect uri to /product/45, since its a generated name, so i have to use appstate, i had the redirect problem with the uninitialized sdk, and i tried loginwithpopup with serve me your error page without additional information. wasnt a good experience.

Can you elaborate on what you are trying to achieve with this? `redirect_uri` is not supposed to be a dynamic URL, your application should have 1 redirect_uri, being the one Auth0 redirects back to after authentication. If you need to, additionally, bring the user back to their previous protected route (e.g. `product/45`), using appState is what you should use and not a limitation of our SDK but the way Auth0 and OAuth works with regards redirect_uri. Could you use our AuthGuard in this case? If you would use the AuthGuard, we automatically use `appState` for u and ensure the user lands back on `product/45`.

I am happy to look into what's going on with the `AuthService` injection and see if we can improve, will track this internally. However, if there is anything further you think we should look into, I recommend opening an issue with all the details for us to understand the specific issue at hand and reproduce the behavior, so we can look into it and address it accordingly.

Closing the issue for now, but as mentioned feel free to open an issue if there are any specific things not working as expected.
