### ISSUE TITLE
"window is not defined" when Auth0 is used with Angular Universal SSR

### ISSUE THREAD

**Issue by CueToDo** [auth0/auth0-angular#432]
### Describe the problem

"window is not defined" when Auth0 is used with Angular Universal SSR

### Reproduction

1. Download sample app and add Angular Universal SSR
2. npm run prerender fails with "window is not defined"

 ReferenceError: window is not defined
    at D:\Development\A0-with-SSR\dist\login-demo\server\main.js:1:4093919
    at D:\Development\A0-with-SSR\dist\login-demo\server\main.js:1:4096144

Full details here - https://stackoverflow.com/questions/75291104/how-can-auth0-be-configured-to-work-with-angular-universal-ssr-starting-from-the

Repo here - https://github.com/CueToDo/A0-with-SSR
Commits - https://github.com/CueToDo/A0-with-SSR/commits/master

### Environment

- **Version of `auth0-angular` used:** 2.0.1
- **Which browsers have you tested in?** Chrome
- **Which version of Angular have you tested with?** 15.1.5
- **Other modules/plugins/libraries that might be involved:** Universal Express/Builders 15.1.0

**Comment by frederikprijck** [comment]
Duplicate #305

See my comment https://github.com/auth0/auth0-angular/issues/305#issuecomment-1118261182

**Comment by CueToDo** [comment]
Hi @frederikprijck,

I see the similar issue #305 you refer to and your comments, however I still can't get Auth0 to work when using SSR. 

I understand that Auth0 is meant to authenticate users which is not required when pre-rendering on the server, therefore it is necessary to guard against calling Auth0 methods on the server.

I began by trying to implement your suggestion: 

> "You want to ensure AuthModule is not imported in the server, you can do this by making a AppClientModule, which imports both AppModule and AuthModule, and remove AuthModule from AppModule."

I think that the issue here is that app.component references app-nav-bar, which imports  AuthService. As the server module bootstraps the AppComponent, there is an indirect call to Auth0 methods.

Referring to [#305 (comment)](https://github.com/auth0/auth0-angular/issues/305#issuecomment-1118261182), I've added a FakeAuthService, imported in the server module and added to providers. I've searched the sample app for any calls on auth and added those methods to FakeAuthService

I'm still getting window is not defined on `npm run prerender`

All I'm trying to do is add Angular SSR to the Auth0 Sample App for Angular. Could you review please for a new issue introduced with Auth0 v2.0.1 perhaps?

I appreciate that issues with Angular Universal are not strictly a concern for Auth0, but as these errors have been seen before, then there must be a relatively simple solution to be able to get Auth0 to work with SSR.

I've updated my repo with latest changes - https://github.com/CueToDo/A0-with-SSR
Commit: https://github.com/CueToDo/A0-with-SSR/commit/b908d299486a0515dfce617a48d7ff0fab5e86cd

Apologies if I've missed the obvious anywhere.

**Comment by frederikprijck** [comment]
The `window is not defined` you are seeing is because of the `HighlightModule`, which is unrelated to our SDK.

Once you remove that, or fix that for SSR, you will get another error:

```
NullInjectorError: No provider for InjectionToken auth0.client!
```

You will also need to mock auth0.client. To avoid that, I would wrap the AuthService from our SDK, and mock that on the server, same as done in the sample I fixed here: https://github.com/rohithart/angular-auth0-ssr/pull/1

**Comment by CueToDo** [comment]
I've spent many more hours trying to get this to work and have failed.

The fixup referenced above no longer works - clicking Login gives "Oops!, something went wrong". Presumably the app config has been updated in the dashboard (?). Running `npm run prerender` fails with `Method Promise.prototype.then called on incompatible receiver [object Object]` (Key to this exercise)

So having also failed to configure the provided sample app to use SSR (https://github.com/CueToDo/A0-with-SSR) I've started again from scratch with a new Angular app created from he CLI (Angular 15). I've added Universal SSR and Auth0. I've then tried to follow carefully the steps provided in the above fixup. I've also googled extensively to get Auth0 v2.0.1 to work with Angular 15.

I've uploaded my latest attempt to GitHub - https://github.com/CueToDo/add-A0-to-SSR

- master branch - I've added Angular Universal - `npm run prerender` works
- Auth0-Login branch - login works (after configuring SSL), prerender fails as expected
- A0-SSR-Fixup branch - login works, prerender fails `Unhandled Promise rejection: NG0204 ; Zone: <root> ; Task: Promise.then`

The steps I've taken are summarised in the app itself, including what is required to use SSL (as http and localhost are no longer permitted in the Auth0 dashboard).

My adaptation has these key steps to prevent import of AuthService on the server

- Create an AuthClientService to wrap the Auth0 Service (not provided in 'root')
- Create an AuthServerService to mock the AuthClientService for the SSR prerendering
- Remove AuthModule from AppModule
- Make an AppClientModule, which imports both AppModule and AuthModule. Provides array includes AuthClientService
- Make an AppServerModule which provides the AuthServerService in place of AuthClientService

Maybe you can refer me to a sample application using Angular 15 and Auth0 v2.0.1, or is there an obvious error in any of the steps I've taken above?

Many thanks and apologies again if I've missed something obvious.

**Comment by frederikprijck** [comment]
> The steps I've taken are summarised in the app itself, including what is required to use SSL (as http and localhost are no longer permitted in the Auth0 dashboard).

I believe that's not accurate, http://localhost should still work fine.

> I've also googled extensively to get Auth0 v2.0.1 to work with Angular 15.

Our official guidance can be found [here ](https://auth0.com/docs/quickstart/spa/angular/interactive)and uses our [official sample](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) that uses Angular 15  and Auth0-Angular v2.x.x.

> Running npm run prerender fails with Method Promise.prototype.then called on incompatible receiver [object Object] (Key to this exercise)

The error you are getting is because of this: https://github.com/CueToDo/add-A0-to-SSR/blob/A0-SSR-Fixup/src/app/modules/app.server.module.ts#L21-L22 and has nothing to do with our SDK or using it with SSR.

You need to change

```
{
  provide:AuthConfigService,
  useClass:{} as any
}
```

to

```
{
  provide:AuthConfigService,
  useValue:{} as any
}
```

`{}` is not a class, but a value. So you can not use it with `useClass`.

That brings you back to the error I mentioned in https://github.com/auth0/auth0-angular/issues/432#issuecomment-1439083525. Which you can solve in a number of ways. However, I decided to drop the wrappers, as I believe you weren't wrapping them the way I think you would want to do it. When wrapping it, you have to use the wrapper everywhere, and you didnt use the in Login and Logout component.

I opened [a PR on your branch](https://github.com/CueToDo/add-A0-to-SSR/pull/1) with changes that I made to make it work. I tested it, prerender works and I can login when using `npm run serve:ssr`.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/2146903/221416417-5ae9f12a-620e-4254-bd3d-6d000efee5eb.png">

Hopefully this makes a bit of sense, and sorry you had to go through such process to get it working. SSR can be difficult in general, especially when integrating libraries not designed for SSR. Hopefully this shows how to make it work.

Important to remember is that this pattern can be used for any library you use that's not designed for SSR, not just our SDK.

**Comment by CueToDo** [comment]
Very many thanks for your time and prompt response - I'll make the updates to my main project asap
