### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by CharlieGreenman** [auth0/auth0-angular#449]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Now that angular 16 released perhaps it makes sense to upgrade this repo. Thank you 

### Describe the ideal solution

Angular 16.0.0 version for auth0

**Comment by frederikprijck** [comment]
👋 Can you elaborate what support you are looking for?

I just upgraded our [sample application](https://github.com/auth0-samples/auth0-angular-samples) from Angular 15 to 16, and it works fine.

I can't merge [the branch](https://github.com/auth0-samples/auth0-angular-samples/tree/feat/ng-16) yet, as there is a dependency of the sample application (HighlightJS) that doesn't work with Angular 16 yet. However, that shouldnt limit you from using our SDK.

You should be able to clone the branch (https://github.com/auth0-samples/auth0-angular-samples/tree/feat/ng-16), run `npm i --force` (we do need force because not all of the sample application libraries are at 16 yet) and be able to succesfully use our SDK.

**Comment by CharlieGreenman** [comment]
ok in that case all systems go. Can mark this ticket as complete. Thank you for your time

**Comment by mdintouch** [comment]
Thanks to everyone involved in fixing this.

**Comment by Fernker** [comment]
I'm confused, this library's package.json shows that it's dependent upon Angular 13:  

https://github.com/auth0/auth0-angular/blob/master/package.json#L33

We are trying to use Angular 14 but aren't able to because this is considered a peer-depedency at a different version then Angular 14.

Is there something I'm missing to use this auth0-angular package with Angular 14+?

**Comment by frederikprijck** [comment]
@Fernker ,

We compile using angular 13, but the peer dependencies are configured to allow anything > 13, see https://github.com/auth0/auth0-angular/blob/master/projects/auth0-angular/package.json#L29

It's tested with angular 13, 14, 15 and 16. What version of the SDK are you using? Can you share a reproduction?

You can find our own example using angular 16 above.
