### ISSUE TITLE
redirectUri does not work properly

### ISSUE THREAD

**Issue by manast** [auth0/auth0-angular#55]
### Describe the problem

```redirectUri```  is not working so it is not possible to redirect the user to some other page after login into the app.

### What was the expected behavior?
User gets redirected after loging in.

### Reproduction
The problem is easily reproducible with the sample application, here the issue: https://github.com/auth0-samples/auth0-angular-samples/issues/206

Tested on Chrome and Firefox latest versions.

**Comment by stevehobbsdev** [comment]
Thanks @manast, the intention here is to use the `AuthGuard` to redirect you to the correct place after login.

On your profile route, add a hook for `canActivate` and give it the `AuthGuard` type. Once login has completed, your user will end up on the Profile page as desired.

Here are the docs: https://github.com/auth0/auth0-angular#protect-a-route

Are you able to get this working? I appreciate the usage of `redirectUri` is a little weird here and I'm looking at what we can do to alleviate that.

**Comment by manast** [comment]
what is the intention of ```redirectUri``` then?

**Comment by manast** [comment]
On the example application it looks like this:
```
import { AuthGuard } from '@auth0/auth0-angular';

const routes: Routes = [
  {
    path: 'profile',
    component: ProfileComponent,
    canActivate: [AuthGuard],
  },
  {
    path: 'external-api',
    component: ExternalApiComponent,
    canActivate: [AuthGuard],
  },
  {
    path: '',
    component: HomeComponent,
    pathMatch: 'full',
  },
];
```
How should I change it to make it work?

**Comment by stevehobbsdev** [comment]
It is indeed to redirect you back to a specific place in your app, but the _preferred_ and native way for you to do that is to use the authentication guard provided in the SDK. Like I said, I'm looking at ways to help clear that usage up.

> How should I change it to make it work?

Those routes look fine. To get this working, simply remove the configuration you're specifying for `redirectUri` and leave it as default.

**Comment by manast** [comment]
I am not sure I follow, If I remove the configuration for ```redirectUri``` it will just stay in the root. I want to redirect the user to ```/profile``` after login.

**Comment by stevehobbsdev** [comment]
> I want to redirect the user to /profile after login.

The Authentication Guard will do this for you if you try to hit `/profile` as an unauthenticated user.

What's your setup? Do you have a login button and you just want to get back to the Profile page every time they log in regardless? One way to achieve this right now before we fix that `redirectUri` usage is have the auth guard in place for `/profile`, and just get your login button to redirect to `/profile`.

**Comment by manast** [comment]
my setup is exactly the one in your demo app, I only did the changes mentioned in the other issue.
I tested earlier that if you try to access ```/profile``` while not being login, the login page appears and after login you are redirected to ```/profile```. The case I am describing is when you start in ```http://localhost:4200``` click on login and then after login you should automatically redirected to ```/profile```.

>  Do you have a login button and you just want to get back to the Profile page every time they log in regardless? One way to achieve this right now before we fix that redirectUri usage is have the auth guard in place for /profile, and just get your login button to redirect to /profile.

That is exactly what I want to do. I get what you mean, it is a bit hackish but if it works I am happy.

**Comment by manast** [comment]
ok, I can confirm the workaround works, thanks.

**Comment by stevehobbsdev** [comment]
Great. In the meantime I will put something together that makes `redirectUri` work a little more as expected 👍

**Comment by manast** [comment]
I can add one more thing though. Using this technique results in a small glitch or jump from the landing page back to your logged in page. What happens is that you click on the login, it redirects you to the protected path, this is not noticeable for the user, good, then you login and it sends you back to the landing, you can see the landing for half a second or so and then redirects you back to the protected path. So to conclude, the proposed solution works but there is still room for improvement.

**Comment by stevehobbsdev** [comment]
Thanks for letting me know. I agree it's not ideal, let me work on something to improve that experience.

**Comment by manast** [comment]
@stevehobbsdev it would be great if you could improve it or if there are any other workaround, currently jumping back to the landing page after login is not very nice, this is my site: https://taskforce.sh/

**Comment by stevehobbsdev** [comment]
@manast Coming back to your use case, will this work for you?

- Set your `redirectUri` to something other than your homepage our your profile page, perhaps something like `https://taskforce.sh/callback`
- Set `appState.target` to your `/profile` route when calling `loginWithRedirect`

So:

```js
// app.module.ts
AuthModule.forRoot({
  domain,
  clientId,
  redirectUri: `${window.location.origin}/callback`
});

// Then when you want to log in
auth.loginWithRedirect({
  appState: {
    target: '/profile'
  }
});
```

Untested, but this should get you what you want without jumping back to your homepage. Your callback page in this case could be blank, or could show a "Please wait while we redirect you" message.

Even if I implement a change to support looking at `redirectUri`, this won't work for you if you're using the `AuthGuard` on that route and also setting your callback URL to that same route. What will happen, is Auth0 will redirect back to `/profile`, hit your route, run the auth guard logic but think you're not logged in yet (because the callback hasn't been handled) and you will end up back at the login page.

You need a page in between the two things that Auth0 can call, if you don't want to simply end up on the home page.

**Comment by manast** [comment]
@stevehobbsdev thanks, your suggestion worked for me.

**Comment by stevehobbsdev** [comment]
Thanks!

**Comment by dbl81** [comment]
Hi @stevehobbsdev,
I'm sorry I'm using this closed issue, but it seems that the issue is still there (feel free to tell me to open another issue if you prefer).

I'm facing the same problem of @manast during an authorization code flow login.

While I think it's important to save a appState before the redirect of the function loginWithRedirect, I'm wondering why the handleRedirectCalllback in the Auth0 service navigates to appState.target (and it chooses to navigate to "/" if the target is undefined):
```
  private handleRedirectCallback(): Observable<RedirectLoginResult> {  
    return defer(() => this.auth0Client.handleRedirectCallback()).pipe(  
      tap((result) => {  
        const target = result?.appState?.target ?? '/';  
        this.navigator.navigateByUrl(target);  
      })  
    );  
  }  
```
I think it should be a choice of the application developer.
Let me explain my thoughts.

The developer of the application knows what to save before the redirect (loginWithRedirect) and he can put the application state into the "appState" parameter of the loginWithRedirect.
The developer has to choose the callback url and he has to configure it in the application setup on auth0.com.
After the login with auth0, the browser is redirect to the callback url where the application developer can wait for the result of /oauth/token POST (emit of isAuthenticated$?) and then he can also run some custom logic he developed (for example get some user preferences from a local database). He doesn't need to have a AuthGuard on the callback route of his application because the custom logic relies on some service which run in a confidential runtime (for example application server or jvm) and the services check if the authorization token is valid before sending back the response.
Then the application developer can choose to redirect the user to the homepage of the application or any other page.

What do you think about that?
Do you see any error?

Thank you.
Gianfelice
