### ISSUE TITLE
AuthGuard + dynamic configuration + root protection

### ISSUE THREAD

**Issue by ThomasPrikrylBE** [auth0/auth0-angular#82]
### Describe the problem

When using the HttpInterceptor and the AuthGuard (on the root route ('')) in combination with a [dynamic configuration](https://github.com/auth0/auth0-angular#dynamic-configuration) that loads a config.json file, I get the error

`Configuration must be specified either through AuthModule.forRoot or through AuthClientConfig.set`

My guess here is, that it is sort of an chicken-and-egg problem: In order to load the configuration file which I would then use to call AuthClientConfig.set with - the HttpInterceptor is triggered (since it's an http call), however since no auth0 config was set at that point yet, this results in the error above.

### What was the expected behavior?

Maybe make it so that the interceptor config can either be set beforehand (before the rest of the config - like domain, clientId, etc...) so that it won't throw an error if no config was set yet when the dynamic configuration is loaded, or make the interceptor only check calls if a config was set, otherwise just do nothing.

### Reproduction

I basically just used the examples from https://github.com/auth0/auth0-angular and combined AuthGuard on AppComponent ('' route), registering an HttpInterceptor and using a dynamic configuration to load a config.json file that contains domain, clientId and redirectUri.

### Environment

> Please provide the following:

- **Version of `auth0-angular` used: 1.2.0
- **Which browsers have you tested in? Chrome
- **Which version of Angular have you tested with? 10.1.6
- **Other modules/plugins/libraries that might be involved: N/A

**Comment by frederikprijck** [comment]
There is not much we can do here. There are ways to tell Angular to not use an Interceptor for a specific request (or you can use fetch or anything else instead of HttpClient).

See: 
- https://github.com/auth0/auth0-angular/issues/70#issuecomment-715225756
- https://medium.com/mikes-fullstack-ladder/how-to-skip-http-interceptor-dee136e54a5f (Solution 2)

> make the interceptor only check calls if a config was set, otherwise just do nothing.

Skipping the interceptor when no config is set might (and will) result in unexpected behavior. The only place this would make sense is in the APP INITIALIZER, where I would recommend using a different solution instead to avoid the unexpected behavior in crucial places in your application.

Closing this, but feel free to continue conversation if this doesn't help.
